# Add key bindings missing in most terminal emulators

key_bindings:
  # Missing key bindings
  - { key: Return,     mods: Shift,         chars: "\x1b[13;2u"    }
  - { key: Return,     mods: Control,       chars: "\x1b[13;5u"    }
  - { key: Tab,        mods: Shift,         chars: "\x1b[9;2u"     }
  - { key: Tab,        mods: Control,       chars: "\x1b[9;5u"     }
  - { key: Period,     mods: Control,       chars: "\x1b[27;5;46~" }
  - { key: Comma,      mods: Control,       chars: "\x1b[27;5;44~" }

  # Control + Shift technically doesn't exist in terminals
  - { key: Tab,        mods: Control|Shift, chars: "\x1b[27;6;9~"    }
  - { key: Return,     mods: Control|Shift, chars: "\x1b[27;6;13~"   }
  - { key: Space,      mods: Control|Shift, chars: "\x1b[27;6;32~"   }
  - { key: Apostrophe, mods: Control|Shift, chars: "\x1b[27;6;39~"   }
  - { key: Comma,      mods: Control|Shift, chars: "\x1b[27;6;44~"   }
  - { key: Minus,      mods: Control|Shift, chars: "\x1b[27;6;45~"   }
  - { key: Period,     mods: Control|Shift, chars: "\x1b[27;6;46~"   }
  - { key: Slash,      mods: Control|Shift, chars: "\x1b[27;6;47~"   }
  - { key: Key0,       mods: Control|Shift, chars: "\x1b[27;6;48~"   }
  - { key: Key1,       mods: Control|Shift, chars: "\x1b[27;6;49~"   }
  - { key: Key2,       mods: Control|Shift, chars: "\x1b[27;6;50~"   }
  - { key: Key3,       mods: Control|Shift, chars: "\x1b[27;6;51~"   }
  - { key: Key4,       mods: Control|Shift, chars: "\x1b[27;6;52~"   }
  - { key: Key5,       mods: Control|Shift, chars: "\x1b[27;6;53~"   }
  - { key: Key6,       mods: Control|Shift, chars: "\x1b[27;6;54~"   }
  - { key: Key7,       mods: Control|Shift, chars: "\x1b[27;6;55~"   }
  - { key: Key8,       mods: Control|Shift, chars: "\x1b[27;6;56~"   }
  - { key: Key9,       mods: Control|Shift, chars: "\x1b[27;6;57~"   }
  - { key: Semicolon,  mods: Control|Shift, chars: "\x1b[27;6;59~"   }
  - { key: Equals,     mods: Control|Shift, chars: "\x1b[27;6;61~"   }
  - { key: A,          mods: Control|Shift, chars: "\x1b[27;6;65~"   }
  - { key: B,          mods: Control|Shift, chars: "\x1b[27;6;66~"   }
  - { key: C,          mods: Control|Shift, chars: "\x1b[27;6;67~"   }
  - { key: D,          mods: Control|Shift, chars: "\x1b[27;6;68~"   }
  - { key: E,          mods: Control|Shift, chars: "\x1b[27;6;69~"   }
  - { key: F,          mods: Control|Shift, chars: "\x1b[27;6;70~"   }
  - { key: G,          mods: Control|Shift, chars: "\x1b[27;6;71~"   }
  - { key: H,          mods: Control|Shift, chars: "\x1b[27;6;72~"   }
  - { key: I,          mods: Control|Shift, chars: "\x1b[27;6;73~"   }
  - { key: J,          mods: Control|Shift, chars: "\x1b[27;6;74~"   }
  - { key: K,          mods: Control|Shift, chars: "\x1b[27;6;75~"   }
  - { key: L,          mods: Control|Shift, chars: "\x1b[27;6;76~"   }
  - { key: M,          mods: Control|Shift, chars: "\x1b[27;6;77~"   }
  - { key: N,          mods: Control|Shift, chars: "\x1b[27;6;78~"   }
  - { key: O,          mods: Control|Shift, chars: "\x1b[27;6;79~"   }
  - { key: P,          mods: Control|Shift, chars: "\x1b[27;6;80~"   }
  - { key: Q,          mods: Control|Shift, chars: "\x1b[27;6;81~"   }
  - { key: R,          mods: Control|Shift, chars: "\x1b[27;6;82~"   }
  - { key: S,          mods: Control|Shift, chars: "\x1b[27;6;83~"   }
  - { key: T,          mods: Control|Shift, chars: "\x1b[27;6;84~"   }
  - { key: U,          mods: Control|Shift, chars: "\x1b[27;6;85~"   }
  - { key: V,          mods: Control|Shift, chars: "\x1b[27;6;86~"   }
  - { key: W,          mods: Control|Shift, chars: "\x1b[27;6;87~"   }
  - { key: X,          mods: Control|Shift, chars: "\x1b[27;6;88~"   }
  - { key: Y,          mods: Control|Shift, chars: "\x1b[27;6;89~"   }
  - { key: Z,          mods: Control|Shift, chars: "\x1b[27;6;90~"   }
  - { key: Backslash,  mods: Control|Shift, chars: "\x1b[27;6;92~"   }

# Alt doesn't exist on Macs (it's option instead)

  # - { key: Tab,        mods: Option, chars: "\x1bTab"    }
  # - { key: Return,     mods: Option, chars: "\x1b"   }
  - { key: Space,      mods: Option, chars: "\x1b "   }
  - { key: Apostrophe, mods: Option, chars: "\x1b'"   }
  - { key: Comma,      mods: Option, chars: "\x1b,"   }
  - { key: Minus,      mods: Option, chars: "\x1b-"   }
  - { key: Period,     mods: Option, chars: "\x1b."   }
  - { key: Slash,      mods: Option, chars: "\x1b/"   }
  - { key: Key0,       mods: Option, chars: "\x1b0"   }
  - { key: Key1,       mods: Option, chars: "\x1b1"   }
  - { key: Key2,       mods: Option, chars: "\x1b2"   }
  - { key: Key3,       mods: Option, chars: "\x1b3"   }
  - { key: Key4,       mods: Option, chars: "\x1b4"   }
  - { key: Key5,       mods: Option, chars: "\x1b5"   }
  - { key: Key6,       mods: Option, chars: "\x1b6"   }
  - { key: Key7,       mods: Option, chars: "\x1b7"   }
  - { key: Key8,       mods: Option, chars: "\x1b8"   }
  - { key: Key9,       mods: Option, chars: "\x1b9"   }
  - { key: Semicolon,  mods: Option, chars: "\x1b;"   }
  - { key: Equals,     mods: Option, chars: "\x1b="   }
  - { key: A,          mods: Option, chars: "\x1ba"   }
  - { key: B,          mods: Option, chars: "\x1bb"   }
  - { key: C,          mods: Option, chars: "\x1bc"   }
  - { key: D,          mods: Option, chars: "\x1bd"   }
  - { key: E,          mods: Option, chars: "\x1be"   }
  - { key: F,          mods: Option, chars: "\x1bf"   }
  - { key: G,          mods: Option, chars: "\x1bg"   }
  - { key: H,          mods: Option, chars: "\x1bh"   }
  - { key: I,          mods: Option, chars: "\x1bi"   }
  - { key: J,          mods: Option, chars: "\x1bj"   }
  - { key: K,          mods: Option, chars: "\x1bk"   }
  - { key: L,          mods: Option, chars: "\x1bl"   }
  - { key: M,          mods: Option, chars: "\x1bm"   }
  - { key: N,          mods: Option, chars: "\x1bn"   }
  - { key: O,          mods: Option, chars: "\x1bo"   }
  - { key: P,          mods: Option, chars: "\x1bp"   }
  - { key: Q,          mods: Option, chars: "\x1bq"   }
  - { key: R,          mods: Option, chars: "\x1br"   }
  - { key: S,          mods: Option, chars: "\x1bs"   }
  - { key: T,          mods: Option, chars: "\x1bt"   }
  - { key: U,          mods: Option, chars: "\x1bu"   }
  - { key: V,          mods: Option, chars: "\x1bv"   }
  - { key: W,          mods: Option, chars: "\x1bw"   }
  - { key: X,          mods: Option, chars: "\x1bx"   }
  - { key: Y,          mods: Option, chars: "\x1by"   }
  - { key: Z,          mods: Option, chars: "\x1bz"   }
  - { key: Backslash,  mods: Option, chars: "\x1b\\"   }
