[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
# NODE_ENV = 'production'

[tools]
# specify single or multiple versions
python = [ '3.11', '3.10']
node = [ 'lts' ]
rust = [ 'stable' ]

[settings] # project-local settings
legacy_version_file = false
always_keep_download = false

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/.config/rtx/config.toml',
]

verbose = false     # see full installation output, see `RTX_VERBOSE`
asdf_compat = true  # ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. default: 4
raw = false         # directly pipe plugins to stdin/stdout/stderr?

experimental = false # enable experimental features
# log_level = 'debug' # log verbosity, see `RTX_LOG_LEVEL`
