- create:
    - ~/.config/git

- link:
    ~/.config/git/config: _init
    ~/.config/git:
        force: true
        glob: true
        path: '*'
        exclude:
            - install.conf.yaml
            - _init

- brew:
    - "git" # Distributed revision control system
    - "git-extras" # Small git utilities
    - "git-filter-repo" # Quickly rewrite git repository history
    - "git-lfs" # Git extension for versioning large files
    - "diff-so-fancy" # Good-lookin' diffs with diff-highlight and more
    - "exiftool" # Perl lib for reading and writing EXIF metadata

- cask:
    - "sublime-merge" # Git client
