---
- name: Bootstrap desktop environment
  hosts: localhost
  vars:
    # general
    home: "{{ '~' | expanduser }}"

    # dotfiles
    dotfiles_home: "{{ home }}/Dotfiles"

    # xdg vars
    config_home: "{{ home }}/.config"
    data_home: "{{ home }}/.local/share"
    cache_home: "{{ home }}/.cache"
    bin_home: "{{ home }}/.local/bin"

    # personal info
    full_name: Jonathan Wren
    computer_user: jonathan
    user_name: wren
    email: jonathan@nowandwren.com
  roles:
    - role: bootstrap
    - role: bat
    - role: 1password
    - role: discord
    - role: git
    # - role: asdf
    - role: neovim
    - role: wezterm
    - role: zsh
