- name: Bootstrap's bootstraps
  hosts: local
  vars:
    # general (probably don't edit)
    home: "{{ '~' | expanduser }}"
    config_home: "{{ home }}/.config"
    data_home: "{{ home }}/.local/share"
    cache_home: "{{ home }}/.cache"
    bin_home: "{{ home }}/.local/bin"

    # personal info (edit here)
    dotfiles_home: "{{ home }}/Dotfiles"
    full_name: Jonathan Wren
    computer_user: jonathan
    github_user_name: wren
    email: jonathan@nowandwren.com
  roles:
    - role: wren.beautiful_output
    - { role: bootstrap, tags: bootstrap }
    - { role: zsh, tags: [cli, shell] }
    - { role: encryption, tags: encryption }
    - { role: 1password, tags: apps }
    - { role: age, tags: cli }
    - { role: mise, tags: cli }
    - { role: bat, tags: cli }
    - { role: borg-backup, tags: backups }
    - { role: discord, tags: apps }
    - { role: doppler, tags: cli }
    # - { role: firefox, tags: apps } # TODO: currently hangs, needs to be fixed
    - { role: fira-code-nerd-font, tags: [cli, fonts] }
    - { role: monolisa-nerd-font, tags: [cli, fonts] }
    - { role: git, tags: cli }
    - { role: itsycal, tags: apps }
    - { role: jrnl, tags: [cli, jrnl] }
    - { role: karabiner, tags: apps }
    - { role: less, tags: cli }
    - { role: lolcat, tags: cli }
    - { role: neovim, tags: [cli, editor] }
    - { role: ripgrep, tags: cli }
    - { role: qmk, tags: keeb }
    - { role: signal, tags: apps }
    - { role: ssh, tags: cli }
    - { role: slack, tags: apps }
    - { role: steam, tags: apps }
    - { role: wezterm, tags: [cli, apps, terminal] }
    - { role: zoom, tags: apps }
    - { role: zoxide, tags: cli }
    - { role: viu, tags: cli }
