---
- name: Bootstrap desktop environment
  hosts: localhost
  vars:
    # general
    home: "{{ '~' | expanduser }}"

    # dotfiles
    dotfiles_home: "{{ home }}/Dotfiles"

    # xdg vars
    config_home: "{{ home }}/.config"
    data_home: "{{ home }}/.local/share"
    cache_home: "{{ home }}/.cache"
    bin_home: "{{ home }}/.local/bin"

    # personal info
    full_name: Jonathan Wren
    computer_user: jonathan
    user_name: wren
    email: jonathan@nowandwren.com
  roles:
    - {role: bootstrap, tags: bootstrap}
    - {role: 1password, tags: 1password}
    - {role: asdf, tags: asdf}
    - {role: bat, tags: bat}
    - {role: discord, tags: discord}
    - {role: fira-code-nerd-font, tags: fira-code-nerd-font}
    - {role: git, tags: git}
    - {role: less, tags: less}
    - {role: neovim, tags: neovim}
    - {role: ripgrep, tags: ripgrep}
    - {role: wezterm, tags: wezterm}
    - {role: zoom, tags: zoom}
    - {role: zoxide, tags: zoxide}
    - {role: viu, tags: viu}
    - {role: zsh, tags: zsh}
