#!/usr/bin/env zsh
set -e

# Config Options
DOTFILES_REPO="https://github.com/wren/dotfiles.git"
DOTBOT_REPO="https://github.com/wren/dotfiles-dotbot.git"

DOTFILES_DIR="${0:A:h}"
DOTBOT_CONFIG="$DOTFILES_DIR/config/dotfiles/dotbot.yaml"
DOTBOT_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotbot"
DOTBOT_PLUGINS_DIR="$DOTBOT_DIR/plugins"
DOTBOT_BIN="$DOTBOT_DIR/dotbot/bin/dotbot"

# Check dotbot directory
if ! git -C "$DOTBOT_DIR" rev-parse &>/dev/null; then
  mkdir -p "$DOTBOT_DIR"
  git clone "$DOTBOT_REPO" "$DOTBOT_DIR" >/dev/null
fi

# Make sure dotbot is updated
cd "$DOTBOT_DIR"
git submodule update --init --recursive --remote >/dev/null

# Prep dotfiles dir
export DOTFILES_DIR

# Check dotfiles directory
if ! git -C "$DOTFILES_DIR" rev-parse &>/dev/null; then
  mkdir -p "$DOTFILES_DIR"
  git clone "$DOTFILES_REPO" "$DOTFILES_DIR" >/dev/null
fi
cd "$DOTFILES_DIR"

# Load all plugins, and run dotbot
CMD="'${DOTBOT_BIN}' -d '${DOTFILES_DIR}' "
  for dir in $DOTBOT_PLUGINS_DIR/*; do
   CMD+="--plugin-dir='$dir' "
  done
CMD+='-c "${DOTBOT_CONFIG}" "${@}"'
eval ${CMD}

