#!/usr/bin/env zsh

echo '----- IP INFO -----'

INTERNAL_IP="$(
  ifconfig | \
  perl -ne 'print $1 if /inet ((?:[0-9]{1,3}\.){3}[0-9]{1,3})/ && $1 !~ /^127/'
)"
echo "Internal: ${INTERNAL_IP:-n/a}"

echo -n 'External: Connecting...'

EXTERNAL_IP="$(
  curl -m 5 -s -H 'Accept: application/json' ipinfo.io | \
  perl -ne 'print $1 if /^\s*"ip": "(.*)",$/'
)"
echo -e "\rExternal: ${EXTERNAL_IP:-n/a           }"
