#!/usr/bin/env zsh

# Use FZF to attach/switch a tmux session

# Get session list
sessions="$(
  tmux ls -F \
  $'#{session_name} #{?session_attached, \uf902,}|#{session_alerts}|#{t:session_activity}|' \
  2>/dev/null
)"

if [[ -z $sessions ]]; then
  echo "No sessions (tmux is not running)."
  echo 'Running `tmux new`'
  tmux new
  return
fi

# send sessions to fzf for choosing
chosen_session="$(
  printf '%s' "$sessions" \
  | perl -pe 's/\d#,?//g' \
  | column -ts'|' \
  | fzf --query="$1" --select-1 --exit-0 \
  | perl -pe 's/^(.*?)\s{3,}.*$/$1/'
)"

if [[ -z $chosen_session ]]; then
  # user cancelled out of fzf
  echo "nope"
  return
fi

local action='attach'
[[ -n $TMUX ]] && action='switch' # already in a tmux session

tmux $action -t "$chosen_session"
