- name: Add i386 architecture
  command:
    cmd: dpkg --add-architecture i386
  become: true

- name: Install dependencies
  with_items:
    - libc6-i386
    - libgl1-nvidia-glx:i386
    - libgl1-mesa-dri:i386
    - libgl1:i386
  apt: "{{ item }}"

- name: "Install: steam"
  apt:
    deb: https://cdn.akamai.steamstatic.com/client/installer/steam.deb
    state: present
