- create:
    - ~/.config/bat
    - ~/.config/batpipe

- brew:
    - "bat" # Clone of cat(1) with syntax highlighting and Git integration
    - "bat-extras" # Bash scripts that integrate bat with various command-line tools

- link:
    ~/.config/bat/bat.config:
        path: 'bat.config'
    ~/.config/batpipe/viewers.d:
        path: 'viewers.d'

