brew "aspell" # Spell checker with better logic than ispell
brew "awscli" # Official Amazon AWS command-line interface
brew "bash" # Bourne-Again SHell, a UNIX command interpreter
brew "bash-completion", link: false # Programmable completion for Bash 3.2
brew "bash-completion@2", link: false # Programmable completion for Bash 4.2+
brew "bash-git-prompt" # Informative, fancy bash prompt for Git users
brew "bat" # Clone of cat(1) with syntax highlighting and Git integration
brew "bats-core" # Bash Automated Testing System
brew "coreutils" # GNU File, Shell, and Text utilities
brew "dasht" # Search API docs offline, in your terminal or browser
brew "diff-so-fancy", args: ["HEAD"] # Good-lookin' diffs with diff-highlight and more
brew "direnv" # Load/unload environment variables based on $PWD
brew "exa" # Modern replacement for 'ls'
brew "exiftool" # Perl lib for reading and writing EXIF metadata
brew "expect" # Program that can automate interactive applications
brew "fd" # Simple, fast and user-friendly alternative to find
brew "findutils" # Collection of GNU find, xargs, and locate
brew "fortune" # Infamous electronic fortune-cookie generator
brew "fzf" # Command-line fuzzy finder written in Go
brew "gawk" # GNU awk utility
brew "gh" # GitHub command-line tool
brew "git" # Distributed revision control system
brew "git-extras" # Small git utilities
brew "git-filter-repo" # Quickly rewrite git repository history
brew "git-lfs" # Git extension for versioning large files
brew "gnu-getopt" # Command-line option parsing utility
brew "gnu-sed" # GNU implementation of the famous stream editor
brew "gnu-tar" # GNU version of the tar archiving utility
brew "gnupg" # GNU Pretty Good Privacy (PGP) package
brew "go" # Open source programming language to build simple/reliable/efficient software
brew "grep" # GNU grep, egrep and fgrep
brew "hub" # Add GitHub support to git on the command-line
brew "hyperfine" # Command-line benchmarking tool
brew "jq" # Lightweight and flexible command-line JSON processor
brew "jrnl", link: false # Command-line note taker
brew "jrnl-org/prerelease/jrnl-beta" # Command-line note taker
brew "kryptco/tap/kr" # Krypton command-line client, daemon, and SSH integration
brew "lolcat" # Rainbows and unicorns in your console!
brew "luajit", args: ["HEAD"] # Just-In-Time Compiler (JIT) for the Lua programming language
brew "luarocks" # Package manager for the Lua programming language
brew "mas" # Mac App Store command-line interface
brew "micro" # Modern and intuitive terminal-based text editor
brew "moreutils" # Collection of tools that nobody wrote when UNIX was young
brew "n" # Node version management
brew "neovim", args: ["HEAD"] # Ambitious Vim-fork focused on extensibility and agility
brew "nmap" # Port scanning utility for large networks
brew "openssh" # OpenBSD freely-licensed SSH connectivity tools
brew "openssl@1.1" # Cryptography and SSL/TLS Toolkit
brew "p7zip" # 7-Zip (high compression file archiver) implementation
brew "pandoc" # Swiss-army knife of markup format conversion
brew "perl" # Highly capable, feature-rich programming language
brew "pipx" # Execute binaries from Python packages in isolated environments
brew "poetry" # Python package management tool
brew "prettyping" # Wrapper to colorize and simplify ping's output
brew "pyenv" # Python version management
brew "pyenv-virtualenv" # Pyenv plugin to manage virtualenv
brew "qmk/qmk/qmk" # Quantum Mechanical Keyboard (QMK) Firmware
brew "rename" # Perl-powered file rename script with many helpful built-ins
brew "ripgrep" # Search tool like grep and The Silver Searcher
brew "rsync" # Utility that provides fast incremental file transfer
brew "secrethub/tools/secrethub-cli" # Command-line interface for SecretHub
brew "shellcheck" # Static analysis and lint tool, for (ba)sh scripts
brew "shfmt" # Autoformat shell script source code
brew "sops" # Editor of encrypted files
brew "sox" # SOund eXchange: universal sound sample translator
brew "tag" # Manipulate and query tags on macOS files
brew "terraform@0.13" # Tool to build, change, and version infrastructure
brew "tmux" # Terminal multiplexer
brew "trash" # CLI tool that moves files or folder to the trash
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"] # Maintained ctags implementation
brew "util-linux" # Collection of Linux utilities
brew "webkit2png" # Create screenshots of webpages from the terminal
brew "wget" # Internet file retriever
brew "youtube-dl" # Download YouTube videos from the command-line
brew "yq" # Process YAML documents from the CLI
brew "zplug" # Next-generation plugin manager for zsh
brew "zsh" # UNIX shell (command interpreter)
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "chromium"
cask "cyberduck"
cask "discord"
cask "docker"
cask "firefox"
cask "flux"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "gitup"
cask "google-chrome"
cask "google-trends"
cask "itsycal"
cask "karabiner-elements"
cask "kitty"
cask "logitech-camera-settings"
cask "pandora"
cask "postman"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlvideo"
cask "qmk-toolbox"
cask "qview"
cask "sequel-pro"
cask "signal"
cask "slack"
cask "spectacle"
cask "the-archive-browser"
cask "the-unarchiver"
cask "vlc"
cask "webpquicklook"
cask "zoom"
cask "zsa-wally"
mas "Skitch", id: 425955336
mas "Xcode", id: 497799835
