- cask:
    - "wez/wezterm/wezterm-nightly"
    - "font-fira-code"
    - "font-fira-code-nerd-font"
    - "font-hack-nerd-font"

- create:
    - ~/.config/wezterm

- link:
    ~/.config/wezterm/wezterm.lua: _init.lua
    ~/.config/wezterm:
        glob: true
        path: '*'
        exclude:
          - install.conf.yaml
          - _init.lua

- shell:
    - description: Update Wezterm Nightly
      command: brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest
