analytics_ids:
    snapshot: ENC[AES256_GCM,data:jh2YZpbji8d0KsYH8NyE6CEdakKajlLaIY6GZCR7NGoG04Ea,iv:M3K7yAlIomYfAF6fsTz9e0k9Mfs2H3Pe0SztkcrU/lI=,tag:Wz0aDy9qOStGK+/obmFQqw==,type:str]
    sync: ENC[AES256_GCM,data:DNHDjC48SiyuFXJ2PAqKs9v3Ez8sNdxq80Rmw4/Uyt0eKmqK,iv:g+gNOpAD3KAtxZb12461JBqZn8tGJZY01eGeww3V6JE=,tag:fQmFf7W0FQtWaItwulQrJw==,type:str]
restic:
    passphrase: ENC[AES256_GCM,data:Bi2ob4RO2qHDy8EQb+3wz+vqjJyoUgosPvbRbYjq4ryut3EArC5T93LwtRLY2v71t+CR2aTP0Wk0aRPUGEDqU/9vMMssUxgqa8HM0Eh+xm7zNAOogyYyd+S0VnkasIgxP+8b1g==,iv:5cwVL3o+awg5h2ab6GDIo3OBrosK3mNq0RkkIHvxtdI=,tag:nVjSHwQrCmR1u67igP8LrQ==,type:str]
    repo: ENC[AES256_GCM,data:VLvWNcLiZrdn,iv:qaMWxp9dLzDPvid1ajJ1bVryD/xrSUKnwDvdMr1MsOM=,tag:37XmRT4r709rvzwOZX/X5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p637gyvk0c0adn9jl3m6u3j2tlym395jkvj0hlpnyxd0pgq7wf3q0xepfw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpenZxN3VueVNENEp3VVA1
            Q25BME04RFpxVzZFM2RQQmpMd0tsRjlKZFcwCmJRcHFTVlJMT0xteDFzTHVnOVZi
            b3ZGWU00NkZQS1NYVE9qNmUyRDkxd2sKLS0tIHlmVjlmUjRQQXBCbXAvWWY0Y09z
            cnZpdkVHa25ZZG95UzBrRDg0TzV5YTAKdc4CAcaBFZ5VnEFatWojkw5cjTw3r5bF
            q5Pnt3/mJUAX+xaE/vTW8P4FKuFHX+qfc1yu78QXkk6NADWuPT7cTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-08-03T04:20:48Z"
    mac: ENC[AES256_GCM,data:A2HyEyKXn73mGq3ey/XkOQzSuQ1ExBMOsI9wMQJWuJ7H4ZbqSO+48NOgYGk1TC1ii7yxqp4andls5R4NGBemcGMNGK5ILPMDBfPbFHY7emk9808uzHiiUS5HcBK6fjpSgzKgtfwJdr9/7bOikv8zCFDxocoWYUsraNQ7y7Tlz74=,iv:gwtWRL873S1m5tTs+/SePFmQ0ub1kwzmqNENlHY2+eY=,tag:Y0JR/hGdbk1VfZ7hj0m9SA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
