{
	"data": "ENC[AES256_GCM,data:nhq1PmCZZH7e1lkqJmUu0qBpldW7yehLzPJM/Z3ejr8Jzgw6z2Rz212rQNebhrGzJeVivZnl9LbECx8LsrBQOEa5iPcaxki9F6AtGig/vY9LIUMekW5YfM8erKn9rYHcUykIHuKtAHXT0ro06+zu/Dg8BFt3k8GamcqW2QUfhp8L8wU+N0+3QCSTNbZE8xHzzobcJG2wUYeWVxVEfOHrTJy5ygXvf8yp0lOU5do3G1sKqSYRlt9Ohmx7ySt6W+3zElwOCUIlDD+y+RWB2IxiRv5PAKDc1a5zZhxvzSV7fx1K0WQT5Ig13RC/zIC1KVgYdLAg9k1mygxoKGRF74LwPBno8PcJysb3gQJN98YRauGfDuIDUA/A6XJf/G7bxi+abN3y/afpmf3qucyUyri+riD55u9A5GCJBYpumXPEkceaSBbX/SHr5fT7JytXSxvQ5nSVwkahcGh1Jbqs,iv:k7j8t6a9UEc2sAUGhWyaIwFuLPsMUJ8KGo/8sS3kOtI=,tag:SnnIccyipIdHJGBpSdmU5A==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1p637gyvk0c0adn9jl3m6u3j2tlym395jkvj0hlpnyxd0pgq7wf3q0xepfw",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vk50c3p2Zi9aR1VVeEwy\nUVJLUnllQWVzQU0xSExFOWJIMUNnelRyNkJrCkVQVFdsZDZuRlZjKzNKQk1GcTBz\nNTkzU1R6S094bUR6U05ITW9IZHJVK2cKLS0tIFk2dlhrSFlBa3MwaC95bTh5aSt5\nTTYrSk5tTVJ4bE9oYzRjdGVudkdEUWsKqjAJdTyaBlIttogYN9EeSpK0hEdTvOg3\nnhy/qBunJxiJEaFyX6Ct5iAndTXfK/dNecQ3Bqyg0hEOYYUC/crCLw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-03-02T16:54:28Z",
		"mac": "ENC[AES256_GCM,data:b0OYPDR8Qwo+eaaT1+NIBOsCoBnRuBVDrZu3pBonzxaRj1KgaHNMmZfrrLiGXfjHo303yTqczsa9VThDITck9QEyWUlauNKYuFctlb/OZlZeAEmtiP38DGejsvwRIBGbEuWkpsvvGEpSpbd/0OFHjhe0Dasn9395P8r633qsezc=,iv:RjOKxAFfe+QR7lGUeX55jH6CpTIIvM+dSHx12e+RkCE=,tag:fuoBuS1xxyyvzc/+xbLTNQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}