- name: Check if lolcat exists
  check_mode: yes
  stat:
    path: "{{ bin_home }}/lolcat"
  register: lolcat

- name: Clone lolcat repo
  git:
    repo: https://github.com/jaseg/lolcat
    dest: /tmp/lolcat
  when: not lolcat.stat.exists

- name: Make lolcat
  command:
    cmd: make lolcat
    chdir: /tmp/lolcat
  when: not lolcat.stat.exists

- name: Install lolcat bin
  become: true
  copy:
    src: /tmp/lolcat/lolcat
    dest: "{{ bin_home }}/lolcat"
    mode: 0755
  when: not lolcat.stat.exists
