- cask:
    - "karabiner-elements" # Keyboard customizer

- create:
    - ~/.config/karabiner

- link:
    ~/.config/karabiner:
        glob: true
        path: '*'
        exclude:
          - install.conf.yaml
