- import_tasks: mac.yaml
  when: ansible_os_family == "Darwin"

- import_tasks: linux.yml
  when: ansible_os_family == "Debian"

- file:
    src: "{{ dotfiles_home }}/roles/zoxide/files/env"
    dest: "{{ config_home }}/env/zoxide.env.sh"
    state: link
