- include_tasks: "{{ role_path }}/tasks/mac.yaml"
  when: ansible_os_family == "Darwin"

# - include_tasks: "{{ dotfiles_home }}/roles/asdf/tasks/linux.yaml"
#   when: ansible_os_family == "Debian"

- name: Create config dir
  file:
    path: "{{ config_home }}/mise"
    state: directory

- name: Link config
  file:
    src: "{{ role_path }}/files/main.toml"
    dest: "{{ config_home }}/mise/config.toml"
    state: link
    force: true

- name: Link env
  file:
    src: "{{ role_path }}/files/env"
    dest: "{{ config_home }}/env/mise.env.sh"
    state: link

- name: Trust config file
  command: mise trust "{{ config_home }}/mise/config.toml"

- name: Install languages
  command:
    cmd: mise install --yes
  register: mise_install_output
  changed_when: "'no runtimes to install' not in mise_install_output.stderr"
