{
	"data": "ENC[AES256_GCM,data:NZ+78plezjDuJ1aLWtquC0hVsMMnjxrVbW7vy4ixlRMYKjpheX4hepCjxkd0qUzu/uMQ6Ew7or22hK9+gSHHjcBi7QU1uqhxm26rdF7/imFNNDT1e6DDzQnTlW/TWyEgLnV9/bwZL/nuN8zB/2Kf0mCI5c+x9y24egC0GfbiyttM1+JyPNwEgXFKMbg3Y15EHgN/CMa6OR1zyX3os2a42mBye+oRJKQuVhS4UP+VX6foSVQkf9O8ceWbMKB/YE7bllsCx7IkDLkRNGTRgFIOe+1ULxnExc2kck7uRN1TvenmgyDcKCfAImscmNyOpL++O8WSN4cUz4hoFddYD8z3wlbfKA/elD9Zc12QGM6TyaJrlI4jPV3WXZRFoS1jOy5OgFCqBiGFJm6RGubGm9h1sarFWtt1h1Uer2EHBPHRYojaSnxq95TMp7YxrdwvZyQv2GgBcEJlDRhuE8qy,iv:A0cQNPq7XQ+OOYyFEG7bjhJ3A/jJnqOAIi3UbW8aPQk=,tag:Cvm+vaCAx6i/M2lmHlt99Q==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1p637gyvk0c0adn9jl3m6u3j2tlym395jkvj0hlpnyxd0pgq7wf3q0xepfw",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ0JUdDRaWGN1N3ZON2tG\nWUp4TVVra0FRN3h0eG96NHJZNks5eW1maEVVCml4dU4rU01ZWHpRV3E0em1BSUNF\nQ0t2eE9oMTR2UGI0Y09HNWhDWEU0YkEKLS0tIGt3ZTFNK0Rxd2EyekxKUmdYOW5u\naWZsS3hBNTJtUmhPVm1SbS82OXFnaEUKnqtCsIvBCgfxwvuvQytvL/3sRjlqAOSh\n103kG+Np1Nk2GLaJhNpt3ZHeJRfLhVxcoJso2MQeu/GldJTWhP5NkA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-03-13T19:59:45Z",
		"mac": "ENC[AES256_GCM,data:yKRCdpnUPUX/0nK+CZF90sh8cBfD/QSQrLQllql8VMI9hwwyK+TNzYzBu20xiiZsHD+uBJ29q5rRjcfbBlLw9mrCkSuTErx+rv7wHCnY0+mlKHAv45E71NlZFjqFZZb/wqRuwTx94pnFL7q1LmUNo0MQzK3VQiV2vBU8u/MZozo=,iv:whRFaVa1TeeOOb04xek9XjDHEapUH2qlmKdCFCOL+Nc=,tag:cNfFfiN/MGYCbXVz/xr7ng==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.1"
	}
}