{
	"data": "ENC[AES256_GCM,data:y8TclWJDj1uDANhrOOBRVOkAvjEYrTz4J7s5tTel2zZ8LimJnIkqiLEi6QPcI7uFuHcGnZIpG4mJ7a2cAJx7cvSsJRsaCkuy5wp/SZYUhZmqw6n9zzYL35dsh9CPFfGk0SaG61QQ5pH7yBjImqUCbz1QScRI/DT11Th9NE3sYUWm+Q+voJIr8IP5whU5TnMkJ1gcACkk3t6m72tckSMtQhiRD52kHlZez3a0aeWcIsQIjq6aV+WUnNg8TifRtavxVdXOQkID4pHYDaFi3QIm7RGkNU3W8oC4aOuGac35v90Ei1upBUsKAWicy2hcPu04DH10ikE99BQ5o0lyL5kr8SHxDRaIjKfNjnHRd6jFFpaaE8RoZYODJSbok7QtEHCMYZgT87CxV73QxGYgP1yWMj8b42tzztO7F7VnHMeSge+UjdxIhcb/p1sb+5q9JgmBMX7vjsMgRKo=,iv:m5CmyoglhbFlrEUH3rAR9rTydjYcCoNA1UnfsIk9guA=,tag:fYVJ2rGQ3v15OU3MdWUfsg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1p637gyvk0c0adn9jl3m6u3j2tlym395jkvj0hlpnyxd0pgq7wf3q0xepfw",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbjJha3AweFFJVWZuMVEz\ndjBES0lhV0xYb21sbnFiaVY1UDBWNGhSTlMwCk9Nb3R2ZXJyUWpjWTIxWDdLdzlT\nM20yV01XVGI5RVpHaThTQjJSQ1J6NkkKLS0tIFBNQW5WOStBRVQ1WGxhOG5WVlV1\nMFRFeGZkVjBuRFVTY2l0dTl1RTh2M2MKYp/hM6ZnwKFTLLcc3fTb2PRp3HveV4YG\nG/8ELuZmZXW4lXv34UKDJIu0NHhgfUbqK3Wp6XqE2vk+qUlofEH2HQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-07-03T19:25:33Z",
		"mac": "ENC[AES256_GCM,data:meZpJ0XObBViVRXatmIJri11H94LNWcpV5I7/2D/J/RmcIlvZwZVyqK/aG6t67+IRpo98w+e+98kJBOZVfjLhdrWwSsHu9/ee8NPQdgVRjxBtlZKi7jFfjTF46ZnNYRjLkcywJ/8wEmfTcSYmXn9S9LPd6K57bHDt80yVR8KtqI=,iv:nCn4YmGvMXs2QMRHGf/3MKQ3qS5ao5k/C5O+Vp6fZm4=,tag:OzFjM4otNY4csX/HpWxGjQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.2"
	}
}