{
	"data": "ENC[AES256_GCM,data:oYh5KoUy1DD/EbkjU2ilzkfCzK7BvJEueo6F5fqA+2yiE8NPnHb7TRRNUv371owaWOKVk8oOawjVdEqAaVq4Bs/6SpkUz6GQJ0abmUHxly94d7Ex2GJApsbFTMMu6CIzdXlCazPVl7DF7qzNXtdr8bdyLv5OtjPRF3TYnwoS9ICy/5qmQizksQ75ZXxkNhHnR4s3CkpkF7fUrz5DgbdKYZKfbt+IXXUg2rUkxwUX2SYVHI8R8crCQREYjnH7dKjIdMks51Kx96vQX/neFztbE+GFlV+5EAiwFu5IhY/pA7OLrs6C49twFeXsXvJOgNdpNfqqySWy6SWB+nMOXYAItpTjuMhc1sCkqkZVhckV9SdoUIuLGZ8s3nn1B/R5R5nxXH9DK7GkF17fyrBfWsGQGH9F1dmEYXB9wwGguQXf5pl09LKhCNtVRIbATzbU52VqW6p331Z7aZw+/mMT,iv:vPX7/ngNe79UkWziFU079TS9HPUUrhI4B6x3I2hV9+U=,tag:VzTs1usWOoDc1J5W1AOKPA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1p637gyvk0c0adn9jl3m6u3j2tlym395jkvj0hlpnyxd0pgq7wf3q0xepfw",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaHpIUmpXczd1MmhDK3Fu\nRzgybkFiYmwwVWxiaXJRUFFWR0lIem5ML1Q4CnZodU51cWwvNkJiY29IZ3hpMGFp\nT0ZwbGRuTUVoVGxzdzNrZVdXL2dlQkUKLS0tIE03eVM3N0ZrU1h2dU9jWjhKdjBF\ncjQ1cVYwVDM2NVJxMHJ1NTBxa0UwTVkKuuy9dCNz04pavVjD29mxwnVoYLPSwc+/\nAO6ZSOrJoGKQahRLG+rq+rnFwOj5qGuizI3OPqt4EuJbEjHL+H8iLw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2022-06-05T20:27:40Z",
		"mac": "ENC[AES256_GCM,data:cfhEsJ+Laa87TFRVxlsl7SwzthMylVQdlq7RIXyrHBH3LjXMwDyUl9bdZejOS5ZhQvkD/51hM0l0M/jDj4WoVPUFtIIdquFEkf1UflmlSLpHU1OjILANB1aG30APqsK0EoC9UKPjTVMU1O8KGYyO503hVuH0EHf9Y3dcbbebDVQ=,iv:I0D6Pvwp5qLTH5UXCBQ40Zl4bbG8rWHc5dcLWk8qHoE=,tag:XGMzzRrj3Mmdg+a2sBwBVQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.2"
	}
}