- name: Install git & friends
  loop:
    - git
    - git-extras
    - git-filter-repo
    - git-lfs
    - libimage-exiftool-perl
    - imagemagick
    - libterm-readkey-perl
  apt:
    name: "{{ item }}"
    state: present
  become: true

- name: Install from homebrew
  homebrew:
    name:
      - diff-so-fancy
    state: present
    update_homebrew: false
