#!/usr/bin/env bash
# DEBUG_DOTFILES="/tmp/dotfiles.$(date +'%F_%T').log" && BASH_START_TIME="$(/usr/local/opt/coreutils/libexec/gnubin/date +%s.%N)"

# Load the shell dotfiles, and then some:
# * ~/.config/bash/extra can be used for other settings you don't want to commit.
dir="${XDG_CONFIG_HOME:-${HOME}/.config}/bash"
files=(
  debug
  xdg
  sensible.bash
  exports
  path
  prompt
  aliases
  functions
  misc
  completion
  extra
)

for file in "${files[@]}"; do
  if [[ -r "$dir/$file" ]]; then
    source "$dir/$file"
    output_time_elapsed "sourced '${file}'"
  fi
done
unset dir file files
output_time_elapsed "Global bash files loaded"

# Determine which host we're on, if possible
my_hostname="default"
for i in $(find "${XDG_CONFIG_HOME}/hosts/" -name 'test.sh'); do
  source "$i"
  [[ "${my_hostname}" =~ ^default$ ]] && [[ -d "${XDG_CONFIG_HOME}/hosts/${my_hostname}" ]] || break
done
output_time_elapsed "Host name determined"

for file in "${XDG_CONFIG_HOME}/hosts/${my_hostname}/"{envvars,sig}.sh; do
  if [ -r "$file" ]; then
    source "$file"
    output_time_elapsed "sourced ${file}"
  fi
done
unset file
output_time_elapsed "Host-specific bash files sourced"

