- name: Install Discord (linux)
  flatpak:
    name: com.discordapp.Discord
    method: system
  when: ansible_os_family == "Debian"

- name: Install Discord (mac)
  homebrew_cask:
    name:
      - discord
    state: present
    update_homebrew: false
  when: ansible_os_family == "Darwin"

