let g:indentline_enabled = 1
let g:indentLine_char_list = []
let g:indentLine_char = '│'
let g:indentLine_first_char = '│'
let g:indentLine_fileTypeExclude = ['defx', 'denite','startify','tagbar','vista_kind','vista']
let g:indentLine_concealcursor = 'c'
let g:indentLine_color_term = 96
let g:indentLine_color_gui = '#5A6872'
let g:indentLine_showFirstIndentLevel = 1
