[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv
# NODE_ENV = 'production'

[tools]
# specify single or multiple versions
python = [ '3.13-dev', '3.12', '3.11' ]
node = [ 'lts', 'latest' ]
rust = [ 'stable' ]
pipx = [ 'latest' ]

[settings] # project-local settings
legacy_version_file = false
always_keep_download = false

# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/.config/mise/config.toml',
]

verbose = false     # see full installation output, see `MISE_VERBOSE`
asdf_compat = true  # ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
jobs = 4            # number of plugins or runtimes to install in parallel. default: 4
raw = false         # directly pipe plugins to stdin/stdout/stderr?

experimental = false # enable experimental features
# log_level = 'debug' # log verbosity, see `MISE_LOG_LEVEL`
