- import_tasks: "{{ dotfiles_home }}/roles/viu/tasks/mac.yaml"
  when: ansible_os_family == "Darwin"

- import_tasks: "{{ dotfiles_home }}/roles/viu/tasks/linux.yaml"
  when: ansible_os_family == "Debian"
